<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>Launchpad</AssemblyName>
    <RootNamespace>Launchpad.App</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <TieredPGO>true</TieredPGO>
    <TieredCompilationQuickJitForLoops>true</TieredCompilationQuickJitForLoops>
    <ApplicationIcon>Assets\launchpad.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <Product>Launchpad</Product>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.IO" />
    <Using Include="System.Linq" />
    <Using Include="System.Threading" />
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Launchpad.Core\Launchpad.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\launchpad.ico" />
  </ItemGroup>

</Project>
