using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Launchpad.App.Native;
using Launchpad.Core.Apps;
using Launchpad.Core.Imaging;

namespace Launchpad.App.Apps;

/// <summary>
/// Everything installed, as the Start menu sees it (classic shortcuts and packaged apps alike). The list and the
/// composed icons are cached on disk, so the launcher can paint instantly and refresh quietly in the background.
/// </summary>
public sealed class AppCatalog
{
    private const int IconVersion = 10;
    private record CachedApp(string Id, string Name, string Target, bool Utility = false, bool Custom = false, bool ShellApplication = false);

    private readonly string _listPath = Path.Combine(AppPaths.DataDir, "apps.json");
    private readonly string _iconDir = Path.Combine(AppPaths.DataDir, "icons");

    public AppCatalog()
    {
        Directory.CreateDirectory(_iconDir);
        // icons generated by older styling versions are never read again
        try
        {
            foreach (string f in Directory.EnumerateFiles(_iconDir, "*.png"))
                if (!f.EndsWith($".v{IconVersion}.png", StringComparison.OrdinalIgnoreCase)) File.Delete(f);
        }
        catch (Exception) { }
    }

    /// <summary>Reads the cached list and icons. Fast; no shell calls.</summary>
    public List<AppItem> LoadCached(IReadOnlyCollection<CustomAppEntry>? customApps = null)
    {
        try
        {
            var cached = File.Exists(_listPath)
                ? JsonSerializer.Deserialize<List<CachedApp>>(File.ReadAllText(_listPath)) ?? new()
                : new List<CachedApp>();
            var items = cached.Select(c => new AppItem(c.Id, c.Name, c.Target, c.Utility, c.Custom, c.ShellApplication)).ToDictionary(i => i.Id);
            if (customApps != null)
                foreach (var entry in customApps)
                    items[entry.Id] = new AppItem(entry.Id, entry.Name, entry.Path, isCustom: true, isShellApplication: entry.IsShellApplication);
            Parallel.ForEach(items.Values, item => item.Icon = LoadIcon(item.Id));
            foreach (var item in items.Values.Where(i => i.IsCustom && i.Icon == null)) item.Icon = LoadCustomIcon(item.Id, item.Target);
            return items.Values.Where(i => i.Icon != null).ToList();
        }
        catch (Exception) { return new(); }
    }

    /// <summary>
    /// Enumerates the shell's app list on a dedicated STA thread. Icons are generated only for apps that don't have one yet
    /// (or all of them when <paramref name="rebuildIcons"/> is set).
    /// </summary>
    public Task<List<AppItem>> RefreshAsync(IReadOnlyCollection<AppItem> existing, bool rebuildIcons = false)
    {
        var tcs = new TaskCompletionSource<List<AppItem>>();
        var thread = new Thread(() =>
        {
            try { tcs.SetResult(Refresh(existing, rebuildIcons)); }
            catch (Exception ex) { tcs.SetException(ex); }
        }) { IsBackground = true, Name = "app-catalog" };
        thread.SetApartmentState(ApartmentState.STA);
        thread.Priority = ThreadPriority.BelowNormal;
        thread.Start();
        return tcs.Task;
    }

    private List<AppItem> Refresh(IReadOnlyCollection<AppItem> existing, bool rebuildIcons)
    {
        var known = existing.ToDictionary(a => a.Id);
        var pinnedIds = existing.Where(a => a.IsCustom).Select(a => a.Id).ToHashSet(StringComparer.OrdinalIgnoreCase);
        var result = new List<AppItem>();

        foreach (var (name, target) in EnumerateShell())
        {
            string id = IdFor(target);
            if (result.Any(r => r.Id == id)) continue;

            ImageSource? icon = null;
            if (!rebuildIcons && known.TryGetValue(id, out var prev)) icon = prev.Icon;
            icon ??= !rebuildIcons ? LoadIcon(id) : null;
            icon ??= BuildIcon(id, target);
            if (icon == null) continue;                     // no icon, nothing sensible to show

            bool pinned = pinnedIds.Contains(id);
            bool shellApplication = pinned && known.TryGetValue(id, out var pinnedItem) && pinnedItem.IsShellApplication;
            bool utility = !pinned && (AppClassifier.IsUtility(name, target) || (Path.IsPathRooted(target) && Directory.Exists(target)));   // explicitly pinned apps belong on the grid
            result.Add(new AppItem(id, name, target, utility, isCustom: pinned, isShellApplication: shellApplication) { Icon = icon });
        }

        foreach (var item in existing.Where(a => a.IsCustom))
        {
            if (result.Any(a => a.Id == item.Id)) continue;
            item.Icon ??= LoadIcon(item.Id) ?? LoadCustomIcon(item.Id, item.Target);
            if (item.Icon != null) result.Add(item);
        }

        result.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.CurrentCultureIgnoreCase));
        Save(result);
        return result;
    }

    // ------------------------------------------------------------------ shell enumeration

    private static IEnumerable<(string name, string target)> EnumerateShell()
    {
        var shellType = Type.GetTypeFromProgID("Shell.Application");
        if (shellType == null) yield break;
        dynamic? shell = Activator.CreateInstance(shellType);
        if (shell == null) yield break;

        var rows = new List<(string, string)>();
        try
        {
            dynamic folder = shell.NameSpace("shell:AppsFolder");
            foreach (dynamic item in folder.Items())
            {
                string name = item.Name ?? "";
                string path = item.Path ?? "";
                if (IsLaunchable(name, path)) rows.Add((name, path));
            }
        }
        catch (Exception) { /* shell unavailable: return what we have */ }

        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var (name, path) in rows)
            if (seen.Add(name + "|" + path)) yield return (name, path);
    }

    private static readonly string[] JunkExtensions = { ".html", ".htm", ".url", ".txt", ".pdf", ".chm", ".rtf", ".md", ".xml", ".ini", ".log" };

    private static bool IsLaunchable(string name, string path)
    {
        if (name.Length == 0 || path.Length == 0) return false;
        if (name.Contains("uninstall", StringComparison.OrdinalIgnoreCase)) return false;
        if (name.Contains("readme", StringComparison.OrdinalIgnoreCase) || name.Contains("release notes", StringComparison.OrdinalIgnoreCase)) return false;
        foreach (string ext in JunkExtensions)
            if (path.EndsWith(ext, StringComparison.OrdinalIgnoreCase)) return false;
        return true;
    }

    // ------------------------------------------------------------------ icons

    private static string IdFor(string target)
    {
        byte[] hash = SHA1.HashData(Encoding.UTF8.GetBytes(target.ToLowerInvariant()));
        return Convert.ToHexString(hash, 0, 8).ToLowerInvariant();
    }

    private string IconPath(string id) => Path.Combine(_iconDir, $"{id}.v{IconVersion}.png");

    private ImageSource? LoadIcon(string id)
    {
        string p = IconPath(id);
        if (!File.Exists(p)) return null;
        try
        {
            using var fs = File.OpenRead(p);
            var decoder = new PngBitmapDecoder(fs, BitmapCreateOptions.PreservePixelFormat, BitmapCacheOption.OnLoad);
            var frame = decoder.Frames[0];
            frame.Freeze();
            return frame;
        }
        catch (Exception) { return null; }
    }

    private ImageSource? BuildIcon(string id, string target, bool custom = false)
    {
        if (!ShellIcons.TryGetBitmap(custom ? target : @"shell:AppsFolder\" + target, 256, out var bgra, out int w, out int h)) return null;
        byte[] px = IconComposer.Compose(bgra, w, h);
        var bmp = BitmapSource.Create(IconComposer.DefaultCanvas, IconComposer.DefaultCanvas, 96, 96, PixelFormats.Pbgra32, null,
            px, IconComposer.DefaultCanvas * 4);
        bmp.Freeze();
        try
        {
            var enc = new PngBitmapEncoder();
            enc.Frames.Add(BitmapFrame.Create(bmp));
            using var fs = File.Create(IconPath(id));
            enc.Save(fs);
        }
        catch (Exception) { /* cache is best-effort */ }
        return bmp;
    }

    private ImageSource? LoadCustomIcon(string id, string path)
    {
        var icon = BuildIcon(id, path, custom: true);
        return icon ?? ShellIcons.ForFile(path, Path.GetExtension(path).TrimStart('.').ToLowerInvariant(), Directory.Exists(path));
    }

    private void Save(List<AppItem> items)
    {
        try
        {
            string json = JsonSerializer.Serialize(items.Select(i => new CachedApp(i.Id, i.Name, i.Target, i.IsUtility, i.IsCustom, i.IsShellApplication)));
            File.WriteAllText(_listPath, json);
        }
        catch (Exception) { }
    }

    // ------------------------------------------------------------------ launching

    public static bool Launch(AppItem app)
    {
        try
        {
            Process.Start(new ProcessStartInfo(app.IsShellApplication || !app.IsCustom ? @"shell:AppsFolder\" + app.Target : app.Target) { UseShellExecute = true });
            return true;
        }
        catch (Exception) { return false; }
    }

    public bool TryCreateCustom(string path, out CustomAppEntry entry, out AppItem item)
    {
        entry = null!;
        item = null!;
        try
        {
            path = Path.GetFullPath(path);
            bool isDirectory = Directory.Exists(path);
            if (!isDirectory && !File.Exists(path)) return false;
            string id = IdFor("custom:" + path);
            string name = isDirectory ? new DirectoryInfo(path).Name : Path.GetFileNameWithoutExtension(path);
            if (string.IsNullOrWhiteSpace(name)) name = path;
            entry = new CustomAppEntry { Id = id, Name = name, Path = path };
            item = new AppItem(id, name, path, isCustom: true) { Icon = LoadCustomIcon(id, path) };
            return item.Icon != null;
        }
        catch (Exception) { return false; }
    }
}

public sealed class CustomAppEntry
{
    public string Id { get; set; } = "";
    public string Name { get; set; } = "";
    public string Path { get; set; } = "";
    public bool IsShellApplication { get; set; }
}
